<div id="sidenav">
	<h4><em>Lab Assignments</em></h4>
	<ul>
		<li><a href="https://www.google.com">Assignment 1</a></li>
		<li><a href="https://www.google.com">Assignment 2</a></li>
		<li><a href="https://www.google.com">Assignment 3</a></li>
		<li><a href="https://www.google.com">Assignment 4</a></li>
	</ul>
	<h4><em>Lab Practica</em></h4>
	<ul>
		<li><a href="https://www.google.com">Practicum 1</a></li>
		<li><a href="https://www.google.com">Practicum 2</a></li>
	</ul>
</div>
