<!--
Jordan Firaben
IT 207 - 002
Menu/Sidenav
-->

<div id="sidenav">
	<a href="/~jfiraben/IT207/index.php">HOME</a>
	<h4><em>Lab Assignments</em></h4>
	<ul>
		<li><a href="/~jfiraben/IT207/assignment1/index.php">Assignment 1</a></li>
		<li><a href="/~jfiraben/IT207/assignment2/index.php">Assignment 2</a></li>
		<li><a href="https://www.google.com">Assignment 3</a></li>
		<li><a href="https://www.google.com">Assignment 4</a></li>
	</ul>
	<h4><em>Lab Practica</em></h4>
	<ul>
		<li><a href="https://www.google.com">Practicum 1</a></li>
		<li><a href="https://www.google.com">Practicum 2</a></li>
	</ul>
</div>
